@startuml
'https://plantuml.com/class-diagram
class ApplicationStart
class ConnectionPool
class Login

ApplicationStart *--> ConnectionPool
Login *--> ConnectionPool

class User
class UserMapper
class UserFacade

class OfferRequest
class OfferRequestMapper
class OfferRequestFacade

class ItemList
class ItemListMapper
class ItemListFacade

UserFacade --> UserMapper
UserMapper --> User

OfferRequestFacade --> OfferRequestMapper
OfferRequestMapper --> OfferRequest

ItemListFacade --> ItemListMapper
ItemListMapper --> ItemList

@enduml

